### ISSUE TITLE
kodi-16.1-4.fc24 crashes

### ISSUE THREAD

**Issue by edgan** [UnitedRPMs/kodi#1]
kodi-16.1-4.fc24 crashed on start. I switched to kodi from RPMFusion, and it works. The previous version, -3 didn't crash, but just gave me garbled video playback.

**Comment by paulcarroty** [comment]
@edgan can you run it in console and paste the log here?

@kuboosoft probably the problem with your integrated ffmpeg.

**Comment by edgan** [comment]
[kodi_crashlog-20160722_205643.txt](https://github.com/UnitedRPMs/kodi/files/379785/kodi_crashlog-20160722_205643.txt)

**Comment by paulcarroty** [comment]
@edgan can you try it's build https://github.com/UnitedRPMs/kodi/releases/tag/16.1-4? It works for me. Thanks again.

**Comment by edgan** [comment]
That is the same build I filed against. Here is a new crash log.

[kodi_crashlog-20160723_083005.txt](https://github.com/UnitedRPMs/kodi/files/379834/kodi_crashlog-20160723_083005.txt)

**Comment by edgan** [comment]
RPMFusion has two patches in their 16.1-2 build. One is a patch for ffmpeg-2.9, but it seems like with it I am working with ffmpeg-3.1 installed. Two a patch for gcc6. Maybe these would help make a non-internal ffmpeg build work without issue.

**Comment by edgan** [comment]
Here are the two patches.

[ffmpeg-2.9.txt](https://github.com/UnitedRPMs/kodi/files/379839/ffmpeg-2.9.txt)
[gcc6.txt](https://github.com/UnitedRPMs/kodi/files/379838/gcc6.txt)

**Comment by edgan** [comment]
Looks like gcc6 is already in kodi-16.1-4. Though now it is ffmpeg-2.9.patch(works) vs kodi-16-ffmpeg3.patch(garbled) vs internal(crash).

**Comment by paulcarroty** [comment]
@edgan kodi 16.1 doesn't support ffmpeg 3.1.1 from URPMS, we use statically linked 2.8.6. 

I now can't understand the problem - it works on my F25, log is very similar: [kodi.log.txt](https://github.com/UnitedRPMs/kodi/files/379845/kodi.log.txt)

Give me the list of your urpms/rpmfusion packages:

```
# dnf list installed | grep -i unitedrpms

# dnf list installed | grep -i rpmfusion
```

**Comment by kuboosoft** [comment]
@edgan see the causes, about the changes..
https://github.com/UnitedRPMs/packages/issues/62
I don't recommend mix it, rpmfusion and UnitedRpms. UnitedRpms has current dependencies.
I'am playing correctly in my machine with F24 and F25 (rawhide)

**Comment by paulcarroty** [comment]
> I'am playing correctly in my machine with F24 and F25 (rawhide)

Now we have 2 working F25 and 1 F24, problem is 100% locally.

**Comment by edgan** [comment]
I have rpmfusion kodi currently installed, because it works. I have ffmpeg installed from unitedrpms.

  @paulcarroty -4 may be ffmpeg 2.8.6 statically linked, but it crashes for me on Fedora 24.

  @kuboosoft I think that is caused by the bad ffmpeg3 patch.

  

unitedrpms:
a52dec.x86_64                          0.7.4-20.fc24            @unitedrpms     
a52dec-devel.x86_64                    0.7.4-20.fc24            @unitedrpms     
                                                                @unitedrpms     
faac.x86_64                            1.28-8.fc24              @unitedrpms     
faad2-devel.x86_64                     1:2.7-7.fc24             @unitedrpms     
faad2-libs.x86_64                      1:2.7-7.fc24             @unitedrpms     
ffmpeg-devel.x86_64                    3.1.1-1.fc24             @unitedrpms     
ffmpeg-libs.x86_64                     3.1.1-1.fc24             @unitedrpms     
freerdp1-libs.x86_64                   1.0.2-3.fc24             @unitedrpms     
gstreamer-plugins-bad.x86_64           0.10.23-8.fc24           @unitedrpms     
gstreamer-plugins-bad-nonfree.x86_64   0.10.23-4.fc24           @unitedrpms     
lame-devel.x86_64                      3.99.5-6.fc24            @unitedrpms     
lame-libs.x86_64                       3.99.5-6.fc24            @unitedrpms     
libavdevice.x86_64                     3.1.1-1.fc24             @unitedrpms     
libdca.x86_64                          0.0.5-11.fc24            @unitedrpms     
libdca-devel.x86_64                    0.0.5-11.fc24            @unitedrpms     
libgcrypt1.5.4.x86_64                  1.5.4-4.fc24             @unitedrpms     
libmpg123.x86_64                       1.23.6-1.fc24            @unitedrpms     
libva-intel-driver.i686                1.7.1-1.fc24             @unitedrpms     
libva-intel-driver.x86_64              1.7.1-1.fc24             @unitedrpms     
live555.x86_64                         2016.06.26-1.fc24        @unitedrpms     
mencoder.x86_64                        1.3.0-3.fc24             @unitedrpms     
mjpegtools-libs.x86_64                 2.1.0-7.fc24             @unitedrpms     
mplayer.x86_64                         1.3.0-3.fc24             @unitedrpms     
mplayer-common.x86_64                  1.3.0-3.fc24             @unitedrpms     
mplayer-gui.x86_64                     1.3.0-3.fc24             @unitedrpms     
mpv.x86_64                             1:0.18.0-5.fc24          @unitedrpms     
mpv-libs.x86_64                        1:0.18.0-5.fc24          @unitedrpms     
opencore-amr.x86_64                    0.1.3-5.fc24             @unitedrpms     
openssl1.x86_64                        1.0.0-4.fc24             @unitedrpms     
                                                                @unitedrpms     
twolame-libs.x86_64                    0.3.13-5.fc24            @unitedrpms     
unitedrpms.noarch                      24-1                     @@commandline   
                                                                @unitedrpms     
                                                                @unitedrpms     
vo-amrwbenc.x86_64                     0.1.3-2.fc24             @unitedrpms     
                                                                @unitedrpms     
zvbi.x86_64                            0.2.35-2.fc24            @unitedrpms     

rpmfusion packages:
amrwb.x86_64                           11.0.0.0-2.fc24          @rpmfusion-nonfree
buildsys-build-rpmfusion.x86_64        10:24-3                  @rpmfusion-free-updates
ffmpeg-compat.x86_64                   0.6.7-9.fc24             @rpmfusion-free 
gstreamer-plugins-ugly.x86_64          0.10.19-19.fc24          @rpmfusion-free 
kodi.x86_64                            16.1-2.fc24              @rpmfusion-free 
                                                                @rpmfusion-free-updates
                                                                @rpmfusion-free-updates
rpmfusion-free-release.noarch          24-1                     @@commandline   
rpmfusion-nonfree-release.noarch       24-1                     @@commandline   
smplayer.x86_64                        16.7.0-1.fc24            @rpmfusion-free-updates
unrar.x86_64                           5.4.2-1.fc24             @rpmfusion-nonfree-updates
                                                                @rpmfusion-free 
xvidcore.x86_64                        1.3.4-2.fc24             @rpmfusion-free

**Comment by edgan** [comment]
I took unitedrpms 16.1-3 src.rpm and replaced kodi-16-ffmpeg3.patch with ffmpeg-2.9.patch. So I am using 16.1, external ffmpeg = 1, and ffmpeg 3.1. This combination works for me.

**Comment by edgan** [comment]
Switched to unitedrpms versions of all packages, or uninstalled the rpmfusion packges with the exception of their repo packages  and buildsys which should have no effect. I reinstalled 16.1-4 and it still crashes.

  My custom 16.1-5 with the ffmpeg-2.9.patch still works.

```
dnf list installed | grep -i rpmfusion                      
buildsys-build-rpmfusion.x86_64        10:24-3                  @rpmfusion-free-updates
rpmfusion-free-release.noarch          24-1                     @@commandline   
rpmfusion-nonfree-release.noarch       24-1                     @@commandline   
```

**Comment by paulcarroty** [comment]
@edgan @kuboosoft I thing we need to test kodi on clear F24.

For complete experiment - @edgan share your *src.rpm if you can.

**Comment by edgan** [comment]
I created a PR #2 with my solution.

**Comment by kuboosoft** [comment]
@paulcarroty  
Are you see? gstreamer-plugins-ugly.x86_64 0.10.19-19.fc24 @rpmfusion-free 
It is other issue, we need change our release, because in rpmfusion uses a previous ffmpeg

**Comment by edgan** [comment]
I tried kodi-16.1-4 and kodi-16.1-5 on my Fedora 24 work laptop. Both work with no issues.

**Comment by kuboosoft** [comment]
Thanks @edgan we need to test, don't worry.

**Comment by paulcarroty** [comment]
> Are you see? gstreamer-plugins-ugly.x86_64 0.10.19-19.fc24 @rpmfusion-free It is other issue

Yep, I see it now @kuboosoft. I'll update it, but we need a complex decision for people who use both fusion/urpms packages:

* use `Epoch: 1` for high priority
* begin releases for 20, 30 etc
* as is

I'm not sure now which variant is better.

**Comment by edgan** [comment]
I also recompiled my src.rpm on my work laptop, and then installed it on my HTPC. It works too. So there isn't any weird dev dependencies on my HTPC affecting the compile.

**Comment by edgan** [comment]
I renaming my ~/.kodi and kodi didn't crash on start. I tried narrowing it down, but ended up finding even with a fresh ~/.kodi it crashed if I try to open the Windows SMB option in files. My normal profile points at my Samba server. I tried making my own build of 16.1-4 on my work laptop to have a cleaner build environment. It still crashes. So there is some weird interaction between switching to internal ffmpeg and Samba. NFS doesn't seem to have the same problem.

**Comment by kuboosoft** [comment]
@paulcarroty  "20" is fine. But as I said the people are mixing rpmfusion and unitedrpms, or we maintain constantly  updated we packages (reason I updated gstreamer1)) or we add in our rpm repository "Conflicts:rpmfusion-free  rpmfusion-free rpmfusion-free-updates-rpmfusion-nonfree-updates" is the easy way...

**Comment by paulcarroty** [comment]
@kuboosoft 

> we add in our rpm repository "Conflicts:rpmfusion-free rpmfusion-nonfree rpmfusion-free-updates rpmfusion-nonfree-updates " is the easy way...

And ask for 100+ issues "Why I can't add rpmfusion? I WANT MOOORE PACKAGES!" Thx, without me. It's funny, but probably fusion maintainers have the same problem :smile: especially with new ffmpeg. We need to think for better decision.

@edgan the config is matter, it's why kodi-4 works in @kuboosoft and me. Probably the problem not in internal/external ffmpeg. Thx for patch, I think to approve it before testing.

Grab all logs and let's talk with upstream.

**Comment by edgan** [comment]
@paulcarroty How does the config matter, and -4 work?

If I rename ~/.Kodi and have -4 installed it will still crash when I try to access the samba option. There is nothing configured, and so it doesn't know about any samba servers from the config.

**Comment by kuboosoft** [comment]
@paulcarroty . I prefer updates! , we have the basic packages for a common user ;) if we import more packages from rpmfusion, the best is merge unitedrpms to rpmfusion because will be the same. Then our efforts in maintain the project outside infraestructure will be death.

**Comment by edgan** [comment]
@kuboosoft Here is a bigger problem. Git is not a good place to keep binaries like rpms and tarballs. Git keeps everything forever. So add a rpm that is 35mb, and the repo is forever 35mb bigger. This will get out of hand with repositories like Kodi. Ten releases in for src rpms or ten versions for tarballs and the repository is 350mb bigger.

GitHub has LFS to handle this problem but it is $5 per 50gb of storage(fine), and 50gb of downloads(potential problem).

A web server would be better. S3 is probably cheap enough, but you would need to do the math. S3+CloudFront would be ideal, but may cost too much. S3+Cloudflare is probably cheaper.

**Comment by x11tete11x** [comment]
Sorry for late answer kodi-16.1-4.fc24.x86_64 working [perfect](http://i.imgur.com/D1ICwv5.png), no issues, even with weird video formats

**Comment by edgan** [comment]
It also crashes on my work laptop with 16.1-4 if I try to access "Windows netowrk(SMB)".

**Comment by x11tete11x** [comment]
I use all UPNP/DLNA after test SMB as @edgan says i can confirm kodi-16.1-4.fc24.x86_64 **fails**


log: 
[kodilog2.txt](https://github.com/UnitedRPMs/kodi/files/380014/kodilog2.txt)

**Comment by kuboosoft** [comment]
@edgan the patch works fine!  but I will testing the internal ffmpeg for emergency issues. The changes will be available in the next hours, please test it.

**Comment by paulcarroty** [comment]
@edgan @kuboosoft  about rpm in git repo - https://github.com/UnitedRPMs/packages/issues/63

Thanks about the service suggestions, our major problem now is cloud for public koji. I'm thinking about [Scaleway](https://www.scaleway.com/), rpmfusion also use it.

**Comment by paulcarroty** [comment]
The latest build with external ffmpeg - let's test: https://github.com/UnitedRPMs/kodi/releases/tag/16.1-5

**Comment by paulcarroty** [comment]
@dcrdev 16.1-5 was added to repo, try it.

**Comment by dcrdev** [comment]
@paulcarroty 16.1-5 has fixed the issue - thanks!
