### ISSUE TITLE
kodi-16.1-4.fc24 smbclient crashes

### ISSUE THREAD

**Issue by dcrdev** [UnitedRPMs/kodi#4]
Currently using the RPMFusion build of Kodi since the UnitedRPMs package crashes every time you attempt to access an smb share.

Nothing is captured in the debug log or crashlog, the process is instantly killed and respawned - the event is captured in the syslog:

[  xx.xxxxx] init: kodi main process (765) killed by ABRT signal.

The RPMFusion build works fine.

**Comment by paulcarroty** [comment]
closed as duplcate -> https://github.com/UnitedRPMs/kodi/issues/1
