### ISSUE TITLE
DVD Recognition Issue

### ISSUE THREAD

**Issue by dcrdev** [UnitedRPMs/kodi#5]
There appears to be an issue with this package of Kodi in relation to auto-mounting of DVDs in that the toggle within Kodi to auto play discs doesn't work for DVD discs; instead Kodi seems to treat DVDs as removable storage i.e. it presents a browse file system menu upon successful mount.

Looking at the debug log Kodi appears to be treating all DVDs universally as having an iso9660 filesystem which is incorrect as the tested DVDs actually have a UDF filesystem.

`13:48:53 T:140144905144832  NOTICE: Log level changed to "LOG_LEVEL_DEBUG_FREEMEM"
13:48:53 T:140144905144832  NOTICE: Enabled debug logging due to GUI setting. Level 2.
13:48:53 T:140144905144832   DEBUG: ------ Window Init () ------
13:48:57 T:140142501164800   DEBUG: Thread JobWorker 140142501164800 terminating (autodelete)
13:48:57 T:140143423903488   DEBUG: Thread JobWorker 140143423903488 terminating (autodelete)
13:48:57 T:140143298078464   DEBUG: Thread JobWorker 140143298078464 terminating (autodelete)
13:49:06 T:140144905144832   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
13:49:11 T:140144905144832   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------
13:49:20 T:140144904775424    INFO: Detecting DVD-ROM media filesystem...
13:49:20 T:140144904775424    INFO: CD Analysis Report
13:49:20 T:140144904775424    INFO: __________________________________
13:49:20 T:140144904775424    INFO: CD-ROM with ISO 9660 filesystem
13:49:20 T:140144904775424    INFO: ISO 9660: 1151849 blocks, label
13:49:20 T:140144904775424    INFO: Tracks overall:1; Audio tracks:0; Data tracks:1
13:49:20 T:140144904775424    INFO: Using protocol iso9660://
13:49:20 T:140144904775424    INFO: Disc label:
13:49:22 T:140144905144832   DEBUG: UDisks: Mounting /org/freedesktop/UDisks/devices/sr0
13:49:23 T:140144905144832   DEBUG: UDisks: Successfully mounted /org/freedesktop/UDisks/devices/sr0 on /media/SUPER_DUPER_ALICE_COOPER
13:49:23 T:140143298078464   DEBUG: Thread JobWorker start, auto delete: true
13:49:23 T:140144905144832   DEBUG: ------ Window Init (DialogSelect.xml) ------
[root@hell01-serv01 temp]#`

Auto-mounting is being achieved via udisks which is in itself correctly recognising the filesystem of the disc:

`[  +1.194618] UDF-fs: INFO Mounting volume 'SUPER_DUPER_ALICE_COOPER', timestamp 2012/12/22 02:42 (1000)`

Kodi does play the disc if you manually select the ts file via the file manager - suggesting that libdvdcss is working (I built that from source) . Additionally Kodi does autoplay CD audio absoloutely fine and whilst I can't rule out it being hardware related I can say that a clean Kodi 16.1 + udisks install on Ubuntu works with the same hardware. I'm wondering if Kodi has been patched here to remove DVD support?

**Comment by kuboosoft** [comment]
@dcrdev The auto-mount of DVD, is a personal task, a DVD/CD/Blue-ray, never is mounted by default.. I recommend make a rule for auto-play.... or install "[ldm-libudev](https://github.com/UnitedRPMs/ldm-libudev/releases)"... also you can test the latest[ Kodi 17](https://github.com/UnitedRPMs/kodi/releases)

**Comment by dcrdev** [comment]
@kuboosoft I think you misunderstand me - auto mounting is already in place on my system and that is achieved via udisks (1 not 2) . The issue is that Kodi itself does not correctly recognise what has been mounted in the case of DVD Video discs.

As you'll see from the Kodi debug log above the disc is successfully mounted under /media/* , from that point the expected behavior from Kodi is that it autoplays the disc, the actual behavior is that it brings up a browse filesystem menu. This is largely because Kodi is incorrectly recognising all DVD video discs as having the wrong filesystem i.e. iso9660 instead of UDF; this behaviour is specific to DVD video discs as Audio CDs, Video CDs all produce the correct behavior.

The incorrect filesystem tagging is isolated to Kodi itself as you'll see from the dmesg output above.

**Comment by kuboosoft** [comment]
Kodi 17 has made some drastically changes; It recognize correctly, what has been mounted in the case of DVD Video discs... I 'am not working with Kodi 16, because have many obsolete code. Kodi in this moment is working with the actual Kodi 17.  I invite you to try.

![](https://s14.postimg.org/719rdo8qp/autoplay.png)

**Comment by dcrdev** [comment]
Ok so I built Kodi 17 from the srpm and it's giving me exactly the same results.

**Comment by paulcarroty** [comment]
@dcrdev beta1 - https://github.com/UnitedRPMs/kodi/releases/tag/17.0b1, your packages is alpha.

**Comment by kuboosoft** [comment]
@dcrdev for me is working fine... if you found the problem, you can send a pull request with the patch... maybe is a problem with your hardware...

**Comment by dcrdev** [comment]
@kuboosoft I'll try beta 1 tomorrow at some point and see if that makes a difference. I don't think it's my hardware as I've tried two different models of drives across 10 or so commercial DVDs. How are you mounting discs, via a window manager?  - I'm using kodi-standalone with udisks.

**Comment by kuboosoft** [comment]
@dcrdev see the changes in Fedora 25... https://fedoraproject.org/wiki/Releases/25/ChangeSet
Replaced UDisks2 by Storaged....

**Comment by dcrdev** [comment]
Yeah again I will try beta 1 tomorrow.

But for clarification I'm using udisks not udisks2, neither storaged, udisks or udisks2 auto mount by themselves; Kodi will automatically mount disks with udisks via dbus if you're running a standalone session i.e I'm launching kodi outside a desktop environment like this:

"/usr/bin/xinit /usr/bin/dbus-launch --exit-with-session /usr/bin/kodi-standalone -- :0 -nolisten"

Kodi still doesn't have support for udisks2 (only udisks or udisks v1) - it definitely doesn't have support for storaged. Based on the screenshot above I'm guessing you're launching Kodi from within GNOME, which is a little bit different, as GNOME will be handling the automount via the gvfs interface.

**Comment by dcrdev** [comment]
Had some unexpected time on my hands -

Beta 1 appears to work! No idea why, it's very peculiar - clearly something has changed mount wise from Alpha 3 to Beta 1.

Thanks for your patience and great work on this - I'll close this now.

**Comment by kuboosoft** [comment]
@dcrdev Don't worry; also the next hours the [kodi-pvr-addons](https://github.com/UnitedRPMs/kodi-pvr-addons/releases) will  ready for the action ;)
