### ISSUE TITLE
no music visualizations

### ISSUE THREAD

**Issue by jalbstmeijer** [UnitedRPMs/kodi#6]
Hi,

Running your Kodi 17b2 packages on Fedora 24. (23 was a typo before)
Is it correct no music visualizations are available? any way to get them?

Gr, J

**Comment by kuboosoft** [comment]
@jalbstmeijer sorry but we only gives you support for F24-F26.  The project does not support Fedora 23. See the site about the project... https://unitedrpms.github.io/

**Comment by paulcarroty** [comment]
@jalbstmeijer try a package from Rpmfusion. I highly recommend to F24-25 upgrade.

@kuboosoft about visualizations - this is our bug or upstream feature? There is 2th bug with this problem.

**Comment by jalbstmeijer** [comment]
Apologies, I meant to say. "Running your Kodi 17b2 packages on Fedora 24".

When googling you see many kodi 16/17 users reporting missing visualizations.
It looks like they get shipped separately starting from kodi 16/17.
So my question was, are you aware and would you be prepared to ship them in a package.

**Comment by sergiomb2** [comment]
Anyway, by curiosity, what we need to have "music visualizations" ? , is used libprojectM ? [1]

[1] https://apps.fedoraproject.org/packages/s/libprojectM

**Comment by kuboosoft** [comment]
@jalbstmeijer why not? I can make a new 'rpm' for it; but I need make a 'meta rpm' with others visualizations addons as spectrum... Only give us time ;)

**Comment by kuboosoft** [comment]
@sergiomb2 only for https://github.com/notspiff/visualization.projectm...

**Comment by kuboosoft** [comment]
Working in a new package....

**Comment by helgrind** [comment]
@kuboosoft any update on this? I've just installed Krypton in our Makerspace on F25 and would love some visualizations like shadertoy. Unfortunately the build is a little out of my depth - I'm not familiar with getting the environment right (addon-dev-kit etc)

**Comment by kuboosoft** [comment]
I can make a rpm for it, but I need time for update various packages; The problem in UnitedRPMs;  we need maintainers. Do you want learn to make rpms? You do not need to be an expert ... I can guide you!

```
cmake \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_BUILD_TYPE=Release \
		-DBUILD_SHARED_LIBS=1 \

	make
make install
```
Generally this way, you compile the visualizations ...

**Comment by helgrind** [comment]
Many thanks!

**Comment by kuboosoft** [comment]
Simple, the first step is read the official guide
https://fedoraproject.org/wiki/How_to_create_an_RPM_package

Next our first exercise with a ".spec" file; the visualizations is a spec more difficult but we can use a simple package. I will update our wiki with some exercises and examples.

----------------------
About the visualizations, you can install all visualizations "dnf install kodi-addon-visualizations". Do not want all, then "dnf install kodi-visualization-spectrum". List [here](https://github.com/UnitedRPMs/kodi-addon-visualizations/blob/master/kodi-addon-visualizations.spec#L28).

**Comment by helgrind** [comment]
Cool, I've worked through the first link and packaged GNU Hello including the i18n and info stuff which makes it a bit less straightforward. Will await your wiki bits specific to unitedrpms

**Comment by kuboosoft** [comment]
@helgrind Generally the task for build rpms in UnitedRPMs, is the same as the wiki of Fedora Project (Excluding the use of fedora infrastructure, and its limitations...)   We need add some exercises to our WIKI, with some templates, all help is welcome.  I have a lot of work, it's bad, I am tired, hahaha. We need to improve our WIKI. Also our english isn't 100% good, help here also will be loved.

**Comment by helgrind** [comment]
Yeah I was looking through some of your build scripts etc and thought I could do some translation bits in there for you at least ;) Thanks, I'll have a look through.

Also, what were the issues with the other visualisations in the newer Fedora release? Is it an easy fix or something nasty?
